### ISSUE TITLE
Support for Inertia::lazy()

### ISSUE THREAD

**Issue by TanguyOS** [boxybird/inertia-wordpress#14]
Hello,

I'm building a framework on top of your adapter and inertia. I'd like to know if you have any plan to add the Inertia::lazy method to the adapter ? Here is the PR on the official adapter for laravel: https://github.com/inertiajs/inertia-laravel/pull/175
And the commit : https://github.com/inertiajs/inertia-laravel/pull/175/commits/53ebf7723f1bac3ca81d6e475dfce381992495df

Would be great to have that feature on wordpress,

Have a nice week-end

**Comment by boxybird** [comment]
Sorry for the delay @TanguyOS. 

This does seem like it would be a nice feature to have, but as of now, I struggling to find the time to work on open-source projects. If I can free up my schedule in the future I'll look into adding it.
