### ISSUE TITLE
Support for SSR

### ISSUE THREAD

**Issue by ngtranthanhtoan** [boxybird/inertia-wordpress#16]
Dear author,

Is there a way to support SSR, since most WordPress websites need SEO friendly?

**Comment by boxybird** [comment]
Hello!

I love the idea, but there are currently no plans to support SSR.

While I do agree with you that typical WordPress sites tend to have a focus on SEO, the goal use case of this adapter was to provide an alternative to the traditional REST API powered SPA, where things like SEO are not as important.

That said, PRs are always welcome!

**Comment by MattPurland** [comment]
I gave this a go, see my PR:

https://github.com/boxybird/inertia-wordpress/pull/21

**Comment by ElvisCaballero** [comment]
Hello!

Awesome work on PR!
I have need for SSR in my page. Whats up with this are there plans to merge it?

**Comment by creative-andrew** [comment]
any love to this @boxybird ?

**Comment by boxybird** [comment]
I pulled this down a while back and had no success getting it running. I'm sure it's a fine implementation, but the nature of WP (and its typical hosting environments) makes running a separate Node process impractical for the bulk of WP installs.

Folking this repo and adding a bespoke SSR solution feels like the win. 

Side thoughts: 

As Laravel continues to innovate, this package's value gets watered-down. Using tools like https://github.com/corcel/corcel make more sense, to me.

Also, as WP leans further into Gutenberg, and its less structured data approach, a tool like this seems useless.
