### ISSUE TITLE
Custom query vars

### ISSUE THREAD

**Issue by merijnponzo** [boxybird/inertia-wordpress#4]
Hi there,
Meanwhile my first wordpress-intertia project is in progress.
However, I'm trying to create filters in my archive page. 

```
function custom_query_vars_filter($vars) {
    $vars[] = 'testing';
    return $vars;
  }
  add_filter( 'query_vars', 'custom_query_vars_filter' );
  ```
  
What happens, with your inertia-wordpress example theme when i visit:
http://inertia.local/movies/?testing=myvar  i got a 301 redirected

When i add the post_type and custom query to a default 'twentynineteen'
http://inertia.local/movies/?testing=myvar it's giving me the proper movies archive page + the testing query var

I could write a custom rest controller for now, but just using the inertia-link would be ideal 
```
<inertia-link href="/filmography" :data="{ filters: 'editorial' }">Editorial Work</inertia-link>
```

**Comment by boxybird** [comment]
Hello @merijnponzo,

I found a couple of things:

1. I was using the global `$wp` object to set the Inertia response URL, which strips any $_GET vars, not good. I just update the logic to use the native REQUEST_URI and all seem well now. 

I haven't merged it into master yet, but the lives in the dev branch (https://github.com/boxybird/inertia-wordpress/tree/dev). Can you confirm it works?

2. The 301 redirect may be a WP permalink issue. If I set my permalinks like this:
![image](https://user-images.githubusercontent.com/18317878/115412236-5dce0c00-a1b1-11eb-8cba-5272a4593f94.png)
Then `https://example.com/movies` won't 301 redirect, but `https://example.com/movies/` will. The trailing slash matters.

Let me know how it goes when you test it!

**Comment by merijnponzo** [comment]
Thank you this totally works, i guess i should be able to create some filters now
the trailing slash is a sharp note and easy to oversee.
